name: Pipeline

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: any
  cancel-in-progress: true

jobs:
  test-server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "22"
          cache: "maven"
      - run: mvn install -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
        working-directory: server_lib
      - run: mvn install -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
        working-directory: server

  test-e2e:
    runs-on: ubuntu-latest
    needs: test-server
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
          cache: "pip"
      - run: pip install -r requirements.txt
      - run: playwright install chromium --with-deps
      - run: ./docker-compose.sh
      - run: pytest
      - name: Upload screenshots
        uses: actions/upload-artifact@v4
        if: failure()
        with:
            name: test-results
            path: test-results
      - run: docker compose logs
        if: always()

  publish-client-lib:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs: test-e2e
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: 3.12
          cache: pip
      - uses: actions/setup-node@v4
        with:
          cache: npm
          cache-dependency-path: client_lib/package-lock.json
      - run: pip install -r requirements.txt
      - run: npm ci
        working-directory: client_lib
      - run: npm run build
        working-directory: client_lib
      - run: scripts/publish_client_lib.py ${{ secrets.GITHUB_TOKEN }} ${{ secrets.ANSIBLE_VAULT_KEY }}
        working-directory: .