name: Pipeline

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: any
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      LOCAL_WORKSPACE_FOLDER: .
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
          cache: "pip"
      - run: pip install -r requirements.txt
      - run: playwright install chromium --with-deps
      - run: cat docker-compose.rj2.yml
      - run: ./docker-compose.sh
      - run: pytest
